import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from '@/components/Navbar'
import Favicon from '../../public/Icons.jpg'
import './globals.css'
import { Toaster } from '@/components/ui/toaster'
import React from 'react'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'MotorInc',
  description: 'Generated by create next app',
  icons: [{rel:'icon', url: Favicon.src}]
}

export default function RootLayout({
  children,
  authModal
}: {
  children: React.ReactNode,
  authModal: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='min-h-screen antialiased'>
        <Navbar />

        {authModal}
        <div className='px-10 mx-auto h-full pt-20'>
        {children}
        </div>

        <Toaster />
        </body>
    </html>
  )
}
